# Farben verbessern
set -g default-terminal "screen-256color"

# Statusbar unten
set -g status-position bottom
set -g status-style bg=black,fg=white

# Prefix leichter erreichbar (optional)
# set -g prefix C-a
# unbind C-b

# Fenster-Nummern bei 1 starten
set -g base-index 1

# Mouse-Support (optional)
set -g mouse on

# Pane-Wechsel mit Alt+Pfeiltasten (kein Prefix!)
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D
run-shell ~/.tmux/plugins/tmux-resurrect/resurrect.tmux
